name: Build and deploy

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: npm install
      - name: Build
        env:
          CI: ""
        run: npm run build
      - name: Deploy
        env:
          REPOSITORY_URL: https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ secrets.USERNAME }}/regxcross
        run: |
          git init
          git config user.name ${{ secrets.USERNAME }}
          git config user.email ${{ secrets.EMAIL }}
          git remote rm origin
          git remote add origin $REPOSITORY_URL
          git fetch --no-recurse-submodules
          LATEST_COMMIT=$(git ls-remote $REPOSITORY_URL main | awk '{print $1}')
          git checkout --progress --force $LATEST_COMMIT
          git fetch $REPOSITORY_URL
          git worktree add --checkout temporary origin/gh-pages
          rm -r temporary/*
          rsync -q -av --checksum --progress dist/. temporary --exclude .ssh --exclude .git --exclude .github
          cd temporary
          git checkout -b temporary
          git status --porcelain
          git add --all .
          git commit -m "Deploying from $LATEST_COMMIT" --quiet
          git push origin -f temporary:gh-pages
          cd ..
          rm -rf temporary
          git worktree remove temporary
